// Copyright (c) 2024 Thirdweb. All Rights Reserved.

#include "Containers/ThirdwebCountryCodes.h"

#define LOCTEXT_NAMESPACE "Thirdweb"
#define LOCTEXT_LOCAL(Value) LOCTEXT(Value, Value)

namespace ThirdwebCountryCodes
{
	const TMap<int32, FThirdwebCountryCode> Map = {
		{376, {376, LOCTEXT_LOCAL("AD"), LOCTEXT_LOCAL("Andorra")}},
		{971, {971, LOCTEXT_LOCAL("AE"), LOCTEXT_LOCAL("United Arab Emirates")}},
		{93, {93, LOCTEXT_LOCAL("AF"), LOCTEXT_LOCAL("Afghanistan")}},
		{1268, {1268, LOCTEXT_LOCAL("AG"), LOCTEXT_LOCAL("Antigua and Barbuda")}},
		{1264, {1264, LOCTEXT_LOCAL("AI"), LOCTEXT_LOCAL("Anguilla")}},
		{355, {355, LOCTEXT_LOCAL("AL"), LOCTEXT_LOCAL("Albania")}},
		{374, {374, LOCTEXT_LOCAL("AM"), LOCTEXT_LOCAL("Armenia")}},
		{599, {599, LOCTEXT_LOCAL("AN"), LOCTEXT_LOCAL("Netherlands Antilles")}},
		{244, {244, LOCTEXT_LOCAL("AO"), LOCTEXT_LOCAL("Angola")}},
		{672, {672, LOCTEXT_LOCAL("AQ"), LOCTEXT_LOCAL("Antarctica")}},
		{54, {54, LOCTEXT_LOCAL("AR"), LOCTEXT_LOCAL("Argentina")}},
		{1684, {1684, LOCTEXT_LOCAL("AS"), LOCTEXT_LOCAL("American Samoa")}},
		{43, {43, LOCTEXT_LOCAL("AT"), LOCTEXT_LOCAL("Austria")}},
		{61, {61, LOCTEXT_LOCAL("AU"), LOCTEXT_LOCAL("Australia")}},
		{297, {297, LOCTEXT_LOCAL("AW"), LOCTEXT_LOCAL("Aruba")}},
		{35818, {35818, LOCTEXT_LOCAL("AX"), LOCTEXT_LOCAL("Aland Islands")}},
		{994, {994, LOCTEXT_LOCAL("AZ"), LOCTEXT_LOCAL("Azerbaijan")}},
		{387, {387, LOCTEXT_LOCAL("BA"), LOCTEXT_LOCAL("Bosnia and Herzegovina")}},
		{1246, {1246, LOCTEXT_LOCAL("BB"), LOCTEXT_LOCAL("Barbados")}},
		{880, {880, LOCTEXT_LOCAL("BD"), LOCTEXT_LOCAL("Bangladesh")}},
		{32, {32, LOCTEXT_LOCAL("BE"), LOCTEXT_LOCAL("Belgium")}},
		{226, {226, LOCTEXT_LOCAL("BF"), LOCTEXT_LOCAL("Burkina Faso")}},
		{359, {359, LOCTEXT_LOCAL("BG"), LOCTEXT_LOCAL("Bulgaria")}},
		{973, {973, LOCTEXT_LOCAL("BH"), LOCTEXT_LOCAL("Bahrain")}},
		{257, {257, LOCTEXT_LOCAL("BI"), LOCTEXT_LOCAL("Burundi")}},
		{229, {229, LOCTEXT_LOCAL("BJ"), LOCTEXT_LOCAL("Benin")}},
		{590, {590, LOCTEXT_LOCAL("BL"), LOCTEXT_LOCAL("Saint Barthelemy")}},
		{1441, {1441, LOCTEXT_LOCAL("BM"), LOCTEXT_LOCAL("Bermuda")}},
		{673, {673, LOCTEXT_LOCAL("BN"), LOCTEXT_LOCAL("Brunei Darussalam")}},
		{591, {591, LOCTEXT_LOCAL("BO"), LOCTEXT_LOCAL("Bolivia")}},
		{55, {55, LOCTEXT_LOCAL("BR"), LOCTEXT_LOCAL("Brazil")}},
		{1242, {1242, LOCTEXT_LOCAL("BS"), LOCTEXT_LOCAL("Bahamas")}},
		{975, {975, LOCTEXT_LOCAL("BT"), LOCTEXT_LOCAL("Bhutan")}},
		{47, {47, LOCTEXT_LOCAL("BV"), LOCTEXT_LOCAL("Bouvet Island")}},
		{267, {267, LOCTEXT_LOCAL("BW"), LOCTEXT_LOCAL("Botswana")}},
		{375, {375, LOCTEXT_LOCAL("BY"), LOCTEXT_LOCAL("Belarus")}},
		{501, {501, LOCTEXT_LOCAL("BZ"), LOCTEXT_LOCAL("Belize")}},
		{1, {1, LOCTEXT_LOCAL("CA"), LOCTEXT_LOCAL("Canada")}},
		{672, {672, LOCTEXT_LOCAL("CC"), LOCTEXT_LOCAL("Cocos (Keeling) Islands")}},
		{236, {236, LOCTEXT_LOCAL("CF"), LOCTEXT_LOCAL("Central African Republic")}},
		{242, {242, LOCTEXT_LOCAL("CG"), LOCTEXT_LOCAL("Congo")}},
		{41, {41, LOCTEXT_LOCAL("CH"), LOCTEXT_LOCAL("Switzerland")}},
		{225, {225, LOCTEXT_LOCAL("CI"), LOCTEXT_LOCAL("Cote d`Ivoire")}},
		{682, {682, LOCTEXT_LOCAL("CK"), LOCTEXT_LOCAL("Cook Islands")}},
		{56, {56, LOCTEXT_LOCAL("CL"), LOCTEXT_LOCAL("Chile")}},
		{237, {237, LOCTEXT_LOCAL("CM"), LOCTEXT_LOCAL("Cameroon")}},
		{86, {86, LOCTEXT_LOCAL("CN"), LOCTEXT_LOCAL("China")}},
		{57, {57, LOCTEXT_LOCAL("CO"), LOCTEXT_LOCAL("Colombia")}},
		{506, {506, LOCTEXT_LOCAL("CR"), LOCTEXT_LOCAL("Costa Rica")}},
		{53, {53, LOCTEXT_LOCAL("CU"), LOCTEXT_LOCAL("Cuba")}},
		{238, {238, LOCTEXT_LOCAL("CV"), LOCTEXT_LOCAL("Cape Verde")}},
		{5999, {5999, LOCTEXT_LOCAL("CW"), LOCTEXT_LOCAL("Curacao")}},
		{6189164, {6189164, LOCTEXT_LOCAL("CX"), LOCTEXT_LOCAL("Christmas Island")}},
		{357, {357, LOCTEXT_LOCAL("CY"), LOCTEXT_LOCAL("Cyprus")}},
		{420, {420, LOCTEXT_LOCAL("CZ"), LOCTEXT_LOCAL("Czechia")}},
		{49, {49, LOCTEXT_LOCAL("DE"), LOCTEXT_LOCAL("Germany")}},
		{253, {253, LOCTEXT_LOCAL("DJ"), LOCTEXT_LOCAL("Djibouti")}},
		{45, {45, LOCTEXT_LOCAL("DK"), LOCTEXT_LOCAL("Denmark")}},
		{1767, {1767, LOCTEXT_LOCAL("DM"), LOCTEXT_LOCAL("Dominica")}},
		{1809, {1809, LOCTEXT_LOCAL("DO"), LOCTEXT_LOCAL("Dominican Republic")}},
		{213, {213, LOCTEXT_LOCAL("DZ"), LOCTEXT_LOCAL("Algeria")}},
		{593, {593, LOCTEXT_LOCAL("EC"), LOCTEXT_LOCAL("Ecuador")}},
		{372, {372, LOCTEXT_LOCAL("EE"), LOCTEXT_LOCAL("Estonia")}},
		{20, {20, LOCTEXT_LOCAL("EG"), LOCTEXT_LOCAL("Egypt")}},
		{212, {212, LOCTEXT_LOCAL("EH"), LOCTEXT_LOCAL("Western Sahara")}},
		{291, {291, LOCTEXT_LOCAL("ER"), LOCTEXT_LOCAL("Eritrea")}},
		{34, {34, LOCTEXT_LOCAL("ES"), LOCTEXT_LOCAL("Spain")}},
		{251, {251, LOCTEXT_LOCAL("ET"), LOCTEXT_LOCAL("Ethiopia")}},
		{358, {358, LOCTEXT_LOCAL("FI"), LOCTEXT_LOCAL("Finland")}},
		{679, {679, LOCTEXT_LOCAL("FJ"), LOCTEXT_LOCAL("Fiji")}},
		{298, {298, LOCTEXT_LOCAL("FO"), LOCTEXT_LOCAL("Faroe Islands")}},
		{33, {33, LOCTEXT_LOCAL("FR"), LOCTEXT_LOCAL("France")}},
		{241, {241, LOCTEXT_LOCAL("GA"), LOCTEXT_LOCAL("Gabon")}},
		{44, {44, LOCTEXT_LOCAL("GB"), LOCTEXT_LOCAL("United Kingdom")}},
		{1473, {1473, LOCTEXT_LOCAL("GD"), LOCTEXT_LOCAL("Grenada")}},
		{995, {995, LOCTEXT_LOCAL("GE"), LOCTEXT_LOCAL("Georgia")}},
		{594, {594, LOCTEXT_LOCAL("GF"), LOCTEXT_LOCAL("French Guiana")}},
		{441481, {441481, LOCTEXT_LOCAL("GG"), LOCTEXT_LOCAL("Guernsey")}},
		{233, {233, LOCTEXT_LOCAL("GH"), LOCTEXT_LOCAL("Ghana")}},
		{350, {350, LOCTEXT_LOCAL("GI"), LOCTEXT_LOCAL("Gibraltar")}},
		{299, {299, LOCTEXT_LOCAL("GL"), LOCTEXT_LOCAL("Greenland")}},
		{220, {220, LOCTEXT_LOCAL("GM"), LOCTEXT_LOCAL("Gambia")}},
		{224, {224, LOCTEXT_LOCAL("GN"), LOCTEXT_LOCAL("Guinea")}},
		{590, {590, LOCTEXT_LOCAL("GP"), LOCTEXT_LOCAL("Guadeloupe")}},
		{240, {240, LOCTEXT_LOCAL("GQ"), LOCTEXT_LOCAL("Equatorial Guinea")}},
		{30, {30, LOCTEXT_LOCAL("GR"), LOCTEXT_LOCAL("Greece")}},
		{502, {502, LOCTEXT_LOCAL("GT"), LOCTEXT_LOCAL("Guatemala")}},
		{1671, {1671, LOCTEXT_LOCAL("GU"), LOCTEXT_LOCAL("Guam")}},
		{245, {245, LOCTEXT_LOCAL("GW"), LOCTEXT_LOCAL("Guinea-Bissau")}},
		{592, {592, LOCTEXT_LOCAL("GY"), LOCTEXT_LOCAL("Guyana")}},
		{504, {504, LOCTEXT_LOCAL("HN"), LOCTEXT_LOCAL("Honduras")}},
		{385, {385, LOCTEXT_LOCAL("HR"), LOCTEXT_LOCAL("Croatia")}},
		{509, {509, LOCTEXT_LOCAL("HT"), LOCTEXT_LOCAL("Haiti")}},
		{36, {36, LOCTEXT_LOCAL("HU"), LOCTEXT_LOCAL("Hungary")}},
		{62, {62, LOCTEXT_LOCAL("ID"), LOCTEXT_LOCAL("Indonesia")}},
		{353, {353, LOCTEXT_LOCAL("IE"), LOCTEXT_LOCAL("Ireland")}},
		{972, {972, LOCTEXT_LOCAL("IL"), LOCTEXT_LOCAL("Israel")}},
		{441624, {441624, LOCTEXT_LOCAL("IM"), LOCTEXT_LOCAL("Isle Of Man")}},
		{91, {91, LOCTEXT_LOCAL("IN"), LOCTEXT_LOCAL("India")}},
		{246, {246, LOCTEXT_LOCAL("IO"), LOCTEXT_LOCAL("British Indian Ocean Territory")}},
		{964, {964, LOCTEXT_LOCAL("IQ"), LOCTEXT_LOCAL("Iraq")}},
		{98, {98, LOCTEXT_LOCAL("IR"), LOCTEXT_LOCAL("Iran (Islamic Republic of)")}},
		{354, {354, LOCTEXT_LOCAL("IS"), LOCTEXT_LOCAL("Iceland")}},
		{39, {39, LOCTEXT_LOCAL("IT"), LOCTEXT_LOCAL("Italy")}},
		{441534, {441534, LOCTEXT_LOCAL("JE"), LOCTEXT_LOCAL("Jersey")}},
		{1876, {1876, LOCTEXT_LOCAL("JM"), LOCTEXT_LOCAL("Jamaica")}},
		{962, {962, LOCTEXT_LOCAL("JO"), LOCTEXT_LOCAL("Jordan")}},
		{81, {81, LOCTEXT_LOCAL("JP"), LOCTEXT_LOCAL("Japan")}},
		{254, {254, LOCTEXT_LOCAL("KE"), LOCTEXT_LOCAL("Kenya")}},
		{996, {996, LOCTEXT_LOCAL("KG"), LOCTEXT_LOCAL("Kyrgyzstan")}},
		{855, {855, LOCTEXT_LOCAL("KH"), LOCTEXT_LOCAL("Cambodia")}},
		{686, {686, LOCTEXT_LOCAL("KI"), LOCTEXT_LOCAL("Kiribati")}},
		{269, {269, LOCTEXT_LOCAL("KM"), LOCTEXT_LOCAL("Comoros")}},
		{1869, {1869, LOCTEXT_LOCAL("KN"), LOCTEXT_LOCAL("Saint Kitts and Nevis")}},
		{82, {82, LOCTEXT_LOCAL("KR"), LOCTEXT_LOCAL("Republic of Korea")}},
		{965, {965, LOCTEXT_LOCAL("KW"), LOCTEXT_LOCAL("Kuwait")}},
		{1345, {1345, LOCTEXT_LOCAL("KY"), LOCTEXT_LOCAL("Cayman Islands")}},
		{7, {7, LOCTEXT_LOCAL("KZ"), LOCTEXT_LOCAL("Kazakhstan")}},
		{961, {961, LOCTEXT_LOCAL("LB"), LOCTEXT_LOCAL("Lebanon")}},
		{1758, {1758, LOCTEXT_LOCAL("LC"), LOCTEXT_LOCAL("Saint Lucia")}},
		{423, {423, LOCTEXT_LOCAL("LI"), LOCTEXT_LOCAL("Liechtenstein")}},
		{94, {94, LOCTEXT_LOCAL("LK"), LOCTEXT_LOCAL("Sri Lanka")}},
		{231, {231, LOCTEXT_LOCAL("LR"), LOCTEXT_LOCAL("Liberia")}},
		{266, {266, LOCTEXT_LOCAL("LS"), LOCTEXT_LOCAL("Lesotho")}},
		{370, {370, LOCTEXT_LOCAL("LT"), LOCTEXT_LOCAL("Lithuania")}},
		{352, {352, LOCTEXT_LOCAL("LU"), LOCTEXT_LOCAL("Luxembourg")}},
		{371, {371, LOCTEXT_LOCAL("LV"), LOCTEXT_LOCAL("Latvia")}},
		{218, {218, LOCTEXT_LOCAL("LY"), LOCTEXT_LOCAL("Libyan Arab Jamahiriya")}},
		{212, {212, LOCTEXT_LOCAL("MA"), LOCTEXT_LOCAL("Morocco")}},
		{377, {377, LOCTEXT_LOCAL("MC"), LOCTEXT_LOCAL("Monaco")}},
		{373, {373, LOCTEXT_LOCAL("MD"), LOCTEXT_LOCAL("Moldova (Republic of)")}},
		{382, {382, LOCTEXT_LOCAL("ME"), LOCTEXT_LOCAL("Montenegro")}},
		{590, {590, LOCTEXT_LOCAL("MF"), LOCTEXT_LOCAL("Saint Martin French")}},
		{261, {261, LOCTEXT_LOCAL("MG"), LOCTEXT_LOCAL("Madagascar")}},
		{692, {692, LOCTEXT_LOCAL("MH"), LOCTEXT_LOCAL("Marshall Islands")}},
		{223, {223, LOCTEXT_LOCAL("ML"), LOCTEXT_LOCAL("Mali")}},
		{95, {95, LOCTEXT_LOCAL("MM"), LOCTEXT_LOCAL("Myanmar")}},
		{976, {976, LOCTEXT_LOCAL("MN"), LOCTEXT_LOCAL("Mongolia")}},
		{1670, {1670, LOCTEXT_LOCAL("MP"), LOCTEXT_LOCAL("Northern Mariana Islands")}},
		{596, {596, LOCTEXT_LOCAL("MQ"), LOCTEXT_LOCAL("Martinique")}},
		{222, {222, LOCTEXT_LOCAL("MR"), LOCTEXT_LOCAL("Mauritania")}},
		{1664, {1664, LOCTEXT_LOCAL("MS"), LOCTEXT_LOCAL("Montserrat")}},
		{356, {356, LOCTEXT_LOCAL("MT"), LOCTEXT_LOCAL("Malta")}},
		{230, {230, LOCTEXT_LOCAL("MU"), LOCTEXT_LOCAL("Mauritius")}},
		{960, {960, LOCTEXT_LOCAL("MV"), LOCTEXT_LOCAL("Maldives")}},
		{265, {265, LOCTEXT_LOCAL("MW"), LOCTEXT_LOCAL("Malawi")}},
		{52, {52, LOCTEXT_LOCAL("MX"), LOCTEXT_LOCAL("Mexico")}},
		{60, {60, LOCTEXT_LOCAL("MY"), LOCTEXT_LOCAL("Malaysia")}},
		{258, {258, LOCTEXT_LOCAL("MZ"), LOCTEXT_LOCAL("Mozambique")}},
		{264, {264, LOCTEXT_LOCAL("NA"), LOCTEXT_LOCAL("Namibia")}},
		{687, {687, LOCTEXT_LOCAL("NC"), LOCTEXT_LOCAL("New Caledonia")}},
		{227, {227, LOCTEXT_LOCAL("NE"), LOCTEXT_LOCAL("Niger")}},
		{672, {672, LOCTEXT_LOCAL("NF"), LOCTEXT_LOCAL("Norfolk Island")}},
		{234, {234, LOCTEXT_LOCAL("NG"), LOCTEXT_LOCAL("Nigeria")}},
		{505, {505, LOCTEXT_LOCAL("NI"), LOCTEXT_LOCAL("Nicaragua")}},
		{31, {31, LOCTEXT_LOCAL("NL"), LOCTEXT_LOCAL("Netherlands")}},
		{47, {47, LOCTEXT_LOCAL("NO"), LOCTEXT_LOCAL("Norway")}},
		{977, {977, LOCTEXT_LOCAL("NP"), LOCTEXT_LOCAL("Nepal")}},
		{674, {674, LOCTEXT_LOCAL("NR"), LOCTEXT_LOCAL("Nauru")}},
		{683, {683, LOCTEXT_LOCAL("NU"), LOCTEXT_LOCAL("Niue")}},
		{64, {64, LOCTEXT_LOCAL("NZ"), LOCTEXT_LOCAL("New Zealand")}},
		{968, {968, LOCTEXT_LOCAL("OM"), LOCTEXT_LOCAL("Oman")}},
		{507, {507, LOCTEXT_LOCAL("PA"), LOCTEXT_LOCAL("Panama")}},
		{51, {51, LOCTEXT_LOCAL("PE"), LOCTEXT_LOCAL("Peru")}},
		{689, {689, LOCTEXT_LOCAL("PF"), LOCTEXT_LOCAL("French Polynesia")}},
		{675, {675, LOCTEXT_LOCAL("PG"), LOCTEXT_LOCAL("Papua New Guinea")}},
		{63, {63, LOCTEXT_LOCAL("PH"), LOCTEXT_LOCAL("Philippines")}},
		{92, {92, LOCTEXT_LOCAL("PK"), LOCTEXT_LOCAL("Pakistan")}},
		{48, {48, LOCTEXT_LOCAL("PL"), LOCTEXT_LOCAL("Poland")}},
		{508, {508, LOCTEXT_LOCAL("PM"), LOCTEXT_LOCAL("Saint Pierre and Miquelon")}},
		{64, {64, LOCTEXT_LOCAL("PN"), LOCTEXT_LOCAL("Pitcairn")}},
		{1787, {1787, LOCTEXT_LOCAL("PR"), LOCTEXT_LOCAL("Puerto Rico")}},
		{351, {351, LOCTEXT_LOCAL("PT"), LOCTEXT_LOCAL("Portugal")}},
		{680, {680, LOCTEXT_LOCAL("PW"), LOCTEXT_LOCAL("Palau")}},
		{595, {595, LOCTEXT_LOCAL("PY"), LOCTEXT_LOCAL("Paraguay")}},
		{974, {974, LOCTEXT_LOCAL("QA"), LOCTEXT_LOCAL("Qatar")}},
		{262, {262, LOCTEXT_LOCAL("RE"), LOCTEXT_LOCAL("Reunion")}},
		{40, {40, LOCTEXT_LOCAL("RO"), LOCTEXT_LOCAL("Romania")}},
		{381, {381, LOCTEXT_LOCAL("RS"), LOCTEXT_LOCAL("Serbia")}},
		{7, {7, LOCTEXT_LOCAL("RU"), LOCTEXT_LOCAL("Russian Federation")}},
		{250, {250, LOCTEXT_LOCAL("RW"), LOCTEXT_LOCAL("Rwanda")}},
		{966, {966, LOCTEXT_LOCAL("SA"), LOCTEXT_LOCAL("Saudi Arabia")}},
		{677, {677, LOCTEXT_LOCAL("SB"), LOCTEXT_LOCAL("Solomon Islands")}},
		{248, {248, LOCTEXT_LOCAL("SC"), LOCTEXT_LOCAL("Seychelles")}},
		{249, {249, LOCTEXT_LOCAL("SD"), LOCTEXT_LOCAL("Sudan")}},
		{46, {46, LOCTEXT_LOCAL("SE"), LOCTEXT_LOCAL("Sweden")}},
		{65, {65, LOCTEXT_LOCAL("SG"), LOCTEXT_LOCAL("Singapore")}},
		{290, {290, LOCTEXT_LOCAL("SH"), LOCTEXT_LOCAL("Saint Helena")}},
		{386, {386, LOCTEXT_LOCAL("SI"), LOCTEXT_LOCAL("Slovenia")}},
		{421, {421, LOCTEXT_LOCAL("SK"), LOCTEXT_LOCAL("Slovakia")}},
		{232, {232, LOCTEXT_LOCAL("SL"), LOCTEXT_LOCAL("Sierra Leone")}},
		{378, {378, LOCTEXT_LOCAL("SM"), LOCTEXT_LOCAL("San Marino")}},
		{221, {221, LOCTEXT_LOCAL("SN"), LOCTEXT_LOCAL("Senegal")}},
		{252, {252, LOCTEXT_LOCAL("SO"), LOCTEXT_LOCAL("Somalia")}},
		{597, {597, LOCTEXT_LOCAL("SR"), LOCTEXT_LOCAL("Suriname")}},
		{211, {211, LOCTEXT_LOCAL("SS"), LOCTEXT_LOCAL("South Sudan")}},
		{239, {239, LOCTEXT_LOCAL("ST"), LOCTEXT_LOCAL("Sao Tome and Principe")}},
		{503, {503, LOCTEXT_LOCAL("SV"), LOCTEXT_LOCAL("El Salvador")}},
		{1721, {1721, LOCTEXT_LOCAL("SX"), LOCTEXT_LOCAL("Sint Maarten Dutch")}},
		{963, {963, LOCTEXT_LOCAL("SY"), LOCTEXT_LOCAL("Syrian Arab Republic")}},
		{268, {268, LOCTEXT_LOCAL("SZ"), LOCTEXT_LOCAL("Swaziland")}},
		{1649, {1649, LOCTEXT_LOCAL("TC"), LOCTEXT_LOCAL("Turks and Caicos Islands")}},
		{235, {235, LOCTEXT_LOCAL("TD"), LOCTEXT_LOCAL("Chad")}},
		{1, {1, LOCTEXT_LOCAL("TF"), LOCTEXT_LOCAL("French Southern Territories")}},
		{228, {228, LOCTEXT_LOCAL("TG"), LOCTEXT_LOCAL("Togo")}},
		{66, {66, LOCTEXT_LOCAL("TH"), LOCTEXT_LOCAL("Thailand")}},
		{992, {992, LOCTEXT_LOCAL("TJ"), LOCTEXT_LOCAL("Tajikistan")}},
		{690, {690, LOCTEXT_LOCAL("TK"), LOCTEXT_LOCAL("Tokelau")}},
		{670, {670, LOCTEXT_LOCAL("TL"), LOCTEXT_LOCAL("Timor-Leste (East Timor)")}},
		{993, {993, LOCTEXT_LOCAL("TM"), LOCTEXT_LOCAL("Turkmenistan")}},
		{216, {216, LOCTEXT_LOCAL("TN"), LOCTEXT_LOCAL("Tunisia")}},
		{676, {676, LOCTEXT_LOCAL("TO"), LOCTEXT_LOCAL("Tonga")}},
		{90, {90, LOCTEXT_LOCAL("TR"), LOCTEXT_LOCAL("Turkey")}},
		{1868, {1868, LOCTEXT_LOCAL("TT"), LOCTEXT_LOCAL("Trinidad and Tobago")}},
		{688, {688, LOCTEXT_LOCAL("TV"), LOCTEXT_LOCAL("Tuvalu")}},
		{886, {886, LOCTEXT_LOCAL("TW"), LOCTEXT_LOCAL("Taiwan (Province of China)")}},
		{255, {255, LOCTEXT_LOCAL("TZ"), LOCTEXT_LOCAL("Tanzania (United Republic of)")}},
		{380, {380, LOCTEXT_LOCAL("UA"), LOCTEXT_LOCAL("Ukraine")}},
		{256, {256, LOCTEXT_LOCAL("UG"), LOCTEXT_LOCAL("Uganda")}},
		{1, {1, LOCTEXT_LOCAL("US"), LOCTEXT_LOCAL("United States")}},
		{598, {598, LOCTEXT_LOCAL("UY"), LOCTEXT_LOCAL("Uruguay")}},
		{998, {998, LOCTEXT_LOCAL("UZ"), LOCTEXT_LOCAL("Uzbekistan")}},
		{58, {58, LOCTEXT_LOCAL("VE"), LOCTEXT_LOCAL("Venezuela")}},
		{1284, {1284, LOCTEXT_LOCAL("VG"), LOCTEXT_LOCAL("Virgin Islands British")}},
		{1340, {1340, LOCTEXT_LOCAL("VI"), LOCTEXT_LOCAL("Virgin Islands US")}},
		{84, {84, LOCTEXT_LOCAL("VN"), LOCTEXT_LOCAL("Vietnam")}},
		{678, {678, LOCTEXT_LOCAL("VU"), LOCTEXT_LOCAL("Vanuatu")}},
		{681, {681, LOCTEXT_LOCAL("WF"), LOCTEXT_LOCAL("Wallis and Futuna Islands")}},
		{685, {685, LOCTEXT_LOCAL("WS"), LOCTEXT_LOCAL("Samoa")}},
		{383, {383, LOCTEXT_LOCAL("XK"), LOCTEXT_LOCAL("Kosovo")}},
		{967, {967, LOCTEXT_LOCAL("YE"), LOCTEXT_LOCAL("Yemen")}},
		{262269, {262269, LOCTEXT_LOCAL("YT"), LOCTEXT_LOCAL("Mayotte")}},
		{38, {38, LOCTEXT_LOCAL("YU"), LOCTEXT_LOCAL("Yugoslavia")}},
		{27, {27, LOCTEXT_LOCAL("ZA"), LOCTEXT_LOCAL("South Africa")}},
		{260, {260, LOCTEXT_LOCAL("ZM"), LOCTEXT_LOCAL("Zambia")}},
		{263, {263, LOCTEXT_LOCAL("ZW"), LOCTEXT_LOCAL("Zimbabwe")}},
	};

	FThirdwebCountryCode GetCountryCodeData(const int32 CountryCode) { return Map.Contains(CountryCode) ? Map[CountryCode] : FThirdwebCountryCode(); }

	TArray<FThirdwebCountryCode> GetCountryCodesArray()
	{
		TArray<FThirdwebCountryCode> CountryCodes;
		Map.GenerateValueArray(CountryCodes);
		return CountryCodes;
	}
}
#undef LOCTEXT_LOCAL
#undef LOCTEXT_NAMESPACE
