// Copyright (c) 2024 Thirdweb. All Rights Reserved.

#include "K2Node/K2Node_ThirdwebBaseAsyncTask.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"

#define LOCTEXT_NAMESPACE "ThirdwebUncookedOnly"

FLinearColor UK2Node_ThirdwebBaseAsyncTask::GetNodeTitleColor() const
{
	return FLinearColor(FColor::FromHex(TEXT("#7207b9")));
}

FSlateIcon UK2Node_ThirdwebBaseAsyncTask::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = FLinearColor(FColor::FromHex(TEXT("#f213a4")));
	static const FSlateIcon Icon = FSlateIcon(FAppStyle::GetAppStyleSetName(), "Kismet.AllClasses.FunctionIcon");;
	return Icon;
}

void UK2Node_ThirdwebBaseAsyncTask::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	UpdatePins();
}

FText UK2Node_ThirdwebBaseAsyncTask::GetMenuCategory() const
{
	return LOCTEXT("K2Node_ThirdwebCreateWallet_Category", "Thirdweb|Wallets");
}

void UK2Node_ThirdwebBaseAsyncTask::PostReconstructNode()
{
	Super::PostReconstructNode();
	UpdatePins();
}

void UK2Node_ThirdwebBaseAsyncTask::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);
	UpdatePins();
}

void UK2Node_ThirdwebBaseAsyncTask::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	Super::GetMenuActions(ActionRegistrar);
	if (UClass* Action = GetClass(); ActionRegistrar.IsOpenForRegistration(Action))
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(GetClass());
		ActionRegistrar.AddBlueprintAction(Action, Spawner);
	}
}

UEdGraphPin* UK2Node_ThirdwebBaseAsyncTask::SetPinVisibility(UEdGraphPin* Pin, const bool bShow)
{
	if (Pin)
	{
		Pin->bHidden = !bShow;
	}
	return Pin;
}


UEdGraphPin* UK2Node_ThirdwebBaseAsyncTask::SetPinFriendlyName(UEdGraphPin* Pin, const FText& FriendlyName)
{
	if (Pin)
	{
		Pin->PinFriendlyName = FriendlyName;
	}
	return Pin;
}

UEdGraphPin* UK2Node_ThirdwebBaseAsyncTask::SetPinConnectable(UEdGraphPin* Pin, const bool bConnectable)
{
	if (Pin)
	{
		Pin->bNotConnectable = !bConnectable;
	}
	return Pin;
}

UEdGraphPin* UK2Node_ThirdwebBaseAsyncTask::SetPinAdvancedView(UEdGraphPin* Pin, const bool bAdvanced)
{
	if (Pin)
	{
		Pin->bAdvancedView = bAdvanced;
	}
	return Pin;
}

void UK2Node_ThirdwebBaseAsyncTask::RemoveHiddenPins(UK2Node* K2Node)
{
	TArray<UEdGraphPin*> Pins = K2Node->Pins;
	for (int i = 0; i < Pins.Num(); i++)
	{
		if (UEdGraphPin* Pin = Pins[i]; Pin && Pin->bHidden)
		{
			UE_LOG(LogTemp, Log, TEXT("K2NodeUtils::DestroyHidden::Destroying unused pin %s"), *Pin->PinName.ToString())
			K2Node->RemovePin(Pin);
		}
	}
}

FString UK2Node_ThirdwebBaseAsyncTask::ResolvePinValue(UEdGraphPin* Pin)
{
	return Pin ? Pin->LinkedTo.Num() > 0 ? Pin->LinkedTo[0]->DefaultValue : Pin->DefaultValue : FString();
}

UEdGraphPin* UK2Node_ThirdwebBaseAsyncTask::SetPinDefaultValue(UEdGraphPin* Pin, const FString& Value)
{
	if (Pin)
	{
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Pin, Value);
	}
	return Pin;
}

void UK2Node_ThirdwebBaseAsyncTask::SetNodeHasAdvanced(const bool bHasAdvanced)
{
	if (bHasAdvanced)
	{
		if (AdvancedPinDisplay == ENodeAdvancedPins::NoPins)
		{
			AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
		}
	}
	else
	{
		AdvancedPinDisplay = ENodeAdvancedPins::NoPins;
	}
}
#undef LOCTEXT_NAMESPACE
