/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace Thirdweb
{

    struct FFIResult
    {
        bool success;
        const char *message;
    };

    extern "C"
    {

        void free_ffi_result(FFIResult result);

        FFIResult create_private_key_wallet(const char *private_key);

        FFIResult generate_private_key_wallet();

        FFIResult create_in_app_wallet(const char *client_id,
                                       const char *bundle_id,
                                       const char *secret_key,
                                       const char *email,
                                       const char *storage_directory_path);

        FFIResult in_app_wallet_send_otp(uintptr_t handle_id);

        FFIResult in_app_wallet_verify_otp(uintptr_t handle_id, const char *otp);

        FFIResult get_wallet_address(uintptr_t handle_id);

        FFIResult sign_message(uintptr_t handle_id, const char *message);

        void free_wallet(uintptr_t handle_id);

        void free_string(char *s);

    } // extern "C"

} // namespace Thirdweb
