// Copyright (c) 2024 Thirdweb. All Rights Reserved.

#pragma once

#include "K2Node_BaseAsyncTask.h"
#include "K2Node_ThirdwebBaseAsyncTask.generated.h"

/**
 * 
 */
UCLASS(Abstract)
class THIRDWEBUNCOOKEDONLY_API UK2Node_ThirdwebBaseAsyncTask : public UK2Node_BaseAsyncTask
{
	GENERATED_BODY()

protected:
	FNodeTextCache CachedNodeTitle;
	
public:
	// UEdGraphNode interface implementation
	virtual FLinearColor GetNodeTitleColor() const override;
	virtual FSlateIcon GetIconAndTint(FLinearColor& OutColor) const override;
	virtual void PinDefaultValueChanged(UEdGraphPin* Pin) override;
	// End of implementation


	// UK2Node interface implementation
	virtual FText GetMenuCategory() const override;
	virtual void PostReconstructNode() override;
	virtual void NotifyPinConnectionListChanged(UEdGraphPin* Pin) override;
	// End of implementation

	virtual void GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const override;
	
protected:
	/** Set the value of `bHidden` on the pin */
	static UEdGraphPin* SetPinVisibility(UEdGraphPin* Pin, const bool bShow);
	
	/** Set the value of `PinFriendlyName` on the pin */
	static UEdGraphPin* SetPinFriendlyName(UEdGraphPin* Pin, const FText& FriendlyName);
	
	/** Set the value of `bNotConnectable` to true on the pin */
	static UEdGraphPin* SetPinConnectable(UEdGraphPin* Pin, const bool bConnectable = false);
	
	/** Set the value of `bAdvancedView` on the pin */
	static UEdGraphPin* SetPinAdvancedView(UEdGraphPin* Pin, const bool bAdvanced = true);
	
	/** Destroy all hidden pins */
	static void RemoveHiddenPins(UK2Node* K2Node);
	
	/** Get the resolved value of the pin */
	static FString ResolvePinValue(UEdGraphPin* Pin);
	
	/** Set the value of `AutogeneratedDefaultValue` on the pin */
	static UEdGraphPin* SetPinDefaultValue(UEdGraphPin* Pin, const FString& Value);
	
	/** Update All pins based on logic */
	virtual void UpdatePins() {}
	/** Set the value of `AdvancedPinDisplay` on the node */
	void SetNodeHasAdvanced(const bool bHasAdvanced);
};
